all: pdf

pdf:
	pdflatex main.tex && pdflatex main.tex

clean:
	-rm -rf *~ *.out *.aux *.dvi *.ps main.pdf *.toc *.lof *.log *.lot *.flg *.bbl *.blg *.idx *.ind *.ilg *.snm *.nav *.fig.bak ./cfg/*.aux ./cfg/*.log *.vrb *.synctex.gz *.el
